### ISSUE TITLE
Add-on does not work in Vaadin 23.2 with Vite

### ISSUE THREAD

**Issue by TatuLund** [stefanuebe/vaadin_fullcalendar#154] opened 2022-09-15 07:09 UTC
Imports using `require `do not work at the moment in Vaadin 23.2 using Vite

![image](https://user-images.githubusercontent.com/14309836/190337888-e91bbfc1-25a0-40ab-ba8e-fca05899e8ae.png)

![image](https://user-images.githubusercontent.com/14309836/190337925-d44e0f65-e761-4f5b-add6-a05e4c32c204.png)

See also: https://github.com/vaadin/flow/issues/14477

The workaround is to use feature flags to use webpack instead of vite.

**Comment by stefanuebe** [comment] 2022-09-21 06:20
Strange as in V23.1 is seemed to have worked with Vite. Going to check that.

**Comment by stefanuebe** [comment] 2022-09-21 06:49
I can start my V23.2 using Vite and the FC without any issues. Can you post the sample code / imports you used for the issue please?

**Comment by stefanuebe** [comment] 2022-09-27 05:55
@aetasoul are you able to reproduce this issue or is it working for you, too?

**Comment by aetasoul** [comment] 2022-09-27 05:59
I will test it as soon as possible, I'm out of office untill friday

**Comment by aetasoul** [comment] 2022-10-03 06:43
unable to reproduce

**Comment by stefanuebe** [comment] 2022-10-04 07:39
Ok, since it seems not to be reproducible, I close this issue until there are new details.

**Closed by stefanuebe** 2022-10-04 07:39 UTC
Labels: bug, workaround
