### ISSUE TITLE
java.time.DateTimeException: Invalid value for NanoOfDay (valid values 0 - 86399999999999)

### ISSUE THREAD

**Issue by danieldubec** [stefanuebe/vaadin_fullcalendar#27] opened 2019-11-20 10:55 UTC
Hi Stefan,
When I add listener with addEntryResizedListener(...) and delta is positive everything is fine, but if delta is negative there is an exception. This will certainly happen with other listeners.
**I think problem is negative value of millis in json** `{"years":0,"months":0,"days":0,"milliseconds":-1800000}`

Exception occurs in class org.vaadin.stefan.fullcalendar.Delta.java in method **fromJson**
```
fromJson(JsonObject jsonObject) {
...
	// new 4.x way
	if (jsonObject.hasKey("milliseconds")) {
		long milliseconds = (long) jsonObject.getNumber("milliseconds");
		LocalTime time = LocalTime.ofNanoOfDay(TimeUnit.MILLISECONDS.toNanos(milliseconds));
		return new Delta(years, months, days, time.getHour(),time.getMinute(),time.getSecond());
	}
...
}
```

Min value in ChronoField is 0
`NANO_OF_DAY("NanoOfDay", ChronoUnit.NANOS, ChronoUnit.DAYS, ValueRange.of(0L, 86399999999999L))`

Exception:

```
Caused by: java.time.DateTimeException: Invalid value for NanoOfDay (valid values 0 - 86399999999999): -1800000000000
	at java.base/java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
	at java.base/java.time.temporal.ChronoField.checkValidValue(ChronoField.java:717)
	at java.base/java.time.LocalTime.ofNanoOfDay(LocalTime.java:398)
	at org.vaadin.stefan.fullcalendar.Delta.fromJson(Delta.java:64)
	at org.vaadin.stefan.fullcalendar.EntryTimeChangedEvent.<init>(EntryTimeChangedEvent.java:39)
	at org.vaadin.stefan.fullcalendar.EntryResizedEvent.<init>(EntryResizedEvent.java:42)
	... 57 more
```

My config is:
* Plain Java Servlet
* calendar - 2.0.0.RC4
* vaadin - 14.0.11

**Comment by kamuffe** [comment] 2019-11-21 14:19
Hi.

I got the same exception with the EntryDroppedListener.
@stefanuebe we talked about that at the Vaadin Dev Day ;)

`
fullCalendar.addEntryDroppedListener( new MyEventMoveHandler() );
`
And now when I move the calendar event the following exception occurs.
`
Caused by: java.time.DateTimeException: Invalid value for NanoOfDay (valid values 0 - 86399999999999): -5400000000000
	at java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311) ~[?:1.8.0_211]
	at java.time.temporal.ChronoField.checkValidValue(ChronoField.java:703) ~[?:1.8.0_211]
	at java.time.LocalTime.ofNanoOfDay(LocalTime.java:376) ~[?:1.8.0_211]
	at org.vaadin.stefan.fullcalendar.Delta.fromJson(Delta.java:64) ~[fullcalendar2-2.0.0.RC4.jar:2.0.0.RC4]
	at org.vaadin.stefan.fullcalendar.EntryTimeChangedEvent.<init>(EntryTimeChangedEvent.java:39) ~[fullcalendar2-2.0.0.RC4.jar:2.0.0.RC4]
	at org.vaadin.stefan.fullcalendar.EntryDroppedEvent.<init>(EntryDroppedEvent.java:41) ~[fullcalendar2-2.0.0.RC4.jar:2.0.0.RC4]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_211]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_211]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_211]
	at com.vaadin.flow.component.ComponentEventBus.createEventForDomEvent(ComponentEventBus.java:409) ~[flow-server-2.0.18.jar:2.0.18]
	... 59 more
`

calendar - 2.0.0.RC4
vaadin - 14.0.13

**Comment by stefanuebe** [comment] 2019-11-22 08:11
I'll check that.

**Comment by stefanuebe** [comment] 2019-11-22 08:41
Will be fixed in next release (RC5 + RC3).

**Closed by stefanuebe** 2019-11-22 08:41 UTC
Labels: bug
